# 数据库连接
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/metro?&serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: Lvsg9410267963
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
spring:
  datasource:
    url: jdbc:hive2://192.168.44.128:10000/szt
    username: hive
    password:
    driver-class-name: org.apache.hive.jdbc.HiveDriver


  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 热部署配置
  devtools:
    restart:
      enable: false
      additional-paths: src/main/java
      exclude: WEB-INF/**
      poll-interval: 20s
      quiet-period: 10s

  #设置文件传输大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.university.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #不删除

server:
  port: 8080

file:
  upload-dir: G:/upload  #
  # FileController 中有个路径也要改成gonghui，就可以对应上

config:
  #  pythonscript
  python-script-path:  E:/论文/地铁分析源码2024/metro_server/src/main/java/com/university/demo/python/pythonscript/
  #  python3
  python-order: python
  # utf-8
  charset-name: gbk